### ISSUE TITLE
What do you think about add a database in the application

### ISSUE THREAD

**Issue by mcruzdev** [salaboy/fmtok8s-c4p#2]
Hello @salaboy 

Like as all microservices, this uses an in-memory approach to save a C4P Object.
I have an idea to change this approach to a realistic approach or more realistic.
In our case, we can add the H2 in-memory SQL database.

What do you think about this?

**Comment by salaboy** [comment]
@mcruzdev let's do that.. if you can have a PR with only adding H2 for now that is a great progress.

**Comment by mcruzdev** [comment]
Okay @salaboy,
I gonna do.

**Comment by salaboy** [comment]
this is done @mcruzdev
