### ISSUE TITLE
I identified that the ContractVerifierTest was not passing

### ISSUE THREAD

**Issue by mcruzdev** [salaboy/fmtok8s-c4p#5]
Was identified that when the system creates a Proposal it returns an object with id as String
But the String does not match with pattern: 

![image](https://user-images.githubusercontent.com/56329339/95494447-501f0a80-0974-11eb-85ea-daae5df4261c.png)

The proposal's id is generated using:
![image](https://user-images.githubusercontent.com/56329339/95494523-6f1d9c80-0974-11eb-9630-e7d7a82c8b5a.png)

I see two ways to solve this problem:

1. Changing the Contract in groovy file
2. Changing the generate method

**Comment by salaboy** [comment]
done
